package com.vmware.pscoe.maven.plugins;

/*
 * #%L
 * common
 * %%
 * Copyright (C) 2023 VMware
 * %%
 * Build Tools for VMware Aria
 * Copyright 2023 VMware, Inc.
 * 
 * This product is licensed to you under the BSD-2 license (the "License"). You may not use this product except in compliance with the BSD-2 License.  
 * 
 * This product may include a number of subcomponents with separate copyright notices and license terms. Your use of these subcomponents is subject to the terms and conditions of the subcomponent's license, as noted in the LICENSE file.
 * #L%
 */

import java.io.File;

import org.apache.maven.project.MavenProject;

public class MavenProjectPackageInfoProvider extends MetadataResolver implements PackageInfoProvider {
    private final String suffix;

    public MavenProjectPackageInfoProvider(MavenProject project) {
        this(project, null);
    }

    public MavenProjectPackageInfoProvider(MavenProject project, String suffix) {
        super(project);
        this.suffix = suffix == null ? "" : suffix;
    }

    @Override
    public String getPackageName() {
        return project.getGroupId() + "." + project.getName() + "-" + project.getVersion() + suffix;
    }

    @Override
    public String getVersion() {
        return project.getVersion();
    }

    @Override
    public String getDescription() {
        return super.extractMetaData(project.getDescription());
    }

    @Override
    public void setDescription(String description) {
        project.setDescription(description);
    }

    public File getSourceDirectory() {
        return new File(project.getBasedir(), "src" + File.separator + "main" + File.separator + "resources");
    }

    /**
     * Returns the directory where the artifact generated by the maven build should be placed after the 'package' goal has been executed.
     * @return The target directory where the artifact would be placed afterh the 'package' goal has been executed.
     */
    public File getTargetDirectory() {
        return new File(project.getModel().getBuild().getDirectory());
    }

}
