name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '⬆️ Dependencies'
    labels:
      - 'dependencies'
exclude-labels:
  - 'skip-changelog'
exclude-contributors:
  - 'svc-wwcoe-ci-admin'
  - 'dependabot'
  - 'dependabot[bot]'
change-template: '* $TITLE by @$AUTHOR in #$NUMBER'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What's Changed

  $CHANGES

  ---
  For in-depth feature set review refer to the following document: https://github.com/vmware/build-tools-for-vmware-aria/blob/main/docs/versions/v$RESOLVED_VERSION/Release.md
  
  **Full Changelog**: https://github.com/vmware/build-tools-for-vmware-aria/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
autolabeler:
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
    title:
      - '/add|implement|support/i'
