#################################################################################
## Common properties (required for all operations)                             ##
#################################################################################

## Common SSL verification properties                                          ##
ignore_ssl_certificate_verification
ignore_ssl_host_verification

## Common timeout properties                                                   ##
http_connection_timeout
http_socket_timeout
vrealize_ssh_timeout

#################################################################################
## Properties for Orchestrator Projects                                        ##
#################################################################################

##  Operation flags. Note that each flag creates a separate session!           ##
vro_import_packages             # imports project bundle packages
vro_delete_last_version         # cleans up project bundle packages
vro_delete_old_versions         # cleans up old versions of bundle packages

## Orchestrator type flag; specifies if host is embedded or standalone/external##
## The value determines the set of connection configuration properties to use! ##
## When embedded, use VCF Automation VM Apps connection configurations         ##
vro_embedded                                        

## Connection configuration                                                    ##
## These properties are used only for standalone/external Orchestrator         ##
## instances (i.e. when "vro_embedded=false")                                  ##
vro_server
vro_port
vro_proxy
# "vro_auth" specifies the authentication type, "basic" or "vra" (VCF Automation)
vro_auth
vro_authHost                    # used only when "vro_auth=vra"
vro_authPort                    # used only when "vro_auth=vra"
vro_refresh_token               # used only when "vro_auth=vra"
vro_username
vro_password
vro_tenant                      # tenant or organization name; can be "null"

## Import configuration - used only for import operation                       ##
## (i.e. when "vro_import_packages=true")                                      ##
vro_enable_backup
vro_import_old_versions
# set "skip_vro_import_old_versions" to opposite value of "vro_import_old_versions"
skip_vro_import_old_versions
vro_import_configuration_attribute_values
vro_import_configuration_secure_attribute_values      
vro_force_import_latest_versions

#################################################################################
## Properties for VCF Automation VM Apps and Aria Automation Projects          ##
#################################################################################

## Operation flags. Note that each flag creates a separate session!            ##
vra_ng_import_packages          # imports project bundle content
vrang_delete_content            # cleans up project bundle content

## Connection configuration                                                    ##
vrang_host
vrang_port
vrang_csp_host                  # optional; set to the value of "vrang_host"
vrang_proxy_required
vrang_proxy                     # used when "vrang_proxy_required=true"
# "vrang_auth_with_refresh_token" specifies the authentication type
vrang_auth_with_refresh_token
vrang_refresh_token             # used when "vrang_auth_with_refresh_token=true"
vrang_username                  # used when "vrang_auth_with_refresh_token=false"
vrang_password                  # used when "vrang_auth_with_refresh_token=false"

## Content management configuration - used for import and clean up operations  ##
## (i.e. when "vra_ng_import_packages=true" or "vrang_delete_content=true")    ##
vrang_project_name
vrang_org_name

## Import configuration - used only for import operation                       ##
## (i.e. when "vra_ng_import_packages=true")                                   ##
vrang_import_overwrite_mode     # optional, can set value to "SKIP"
# "vrang_vro_integration_name" specifies the integration endpoint for Workflow
# Content Sources and other resources that point to that type of integration.
# If the property is missing, the default name "embedded-VRO" is used
vrang_vro_integration_name
# "vrang_import_timeout" sets the timeout (in milliseconds) for the
# synchronization of the content source and custom forms
vrang_import_timeout
# "vrang_data.collection.delay.seconds" sets the delay (wait time in seconds)
# for the data collection of the Orchestrator integration so the import of
# Automation content that depends on Orchestrator objects can succeed.
# When the property is provided, the script forces data collection for the
# integration and only if this fails, the script uses the delay.
vrang_data.collection.delay.seconds
vrang_bp_unrelease_versions

#################################################################################
## Properties for ABX Projects (VCF Automation VM Apps and Aria Automation)    ##
#################################################################################

## Operation flag                                                              ##
abx_import_packages             # imports project bundle content
# NOTE: When importing ABX content, the script unpacks all ABX modules and      #
# imports them iteratively                                                      #

## Configuration properties                                                    ##
# Use all properties from the "Connection configuration" group and the "Content
# management configuration" groups for VCF Automation VM Apps and Aria Automation
# There are no additional configuration properties for ABX content

#################################################################################
## Properties for Code Stream/Pipelines Projects (Aria Automation)             ##
#################################################################################
## This project type is supported only for Aria Automation (v8.x)              ##

## Operation flag                                                              ##
cs_import_packages              # imports project bundle content

## Configuration properties                                                    ##
# Use all properties from the "Connection configuration" group and the "Content
# management configuration" groups for VCF Automation VM Apps and Aria Automation
# together with the following property
vrang_cloud_proxy_name

#################################################################################
## Properties for VCF Automation All Apps Projects                             ##
#################################################################################

## Operation flags. Note that each flag creates a separate session!            ##
vcfaa_import_packages           # imports project bundle content
vcfa_delete_content             # cleans up project bundle content

## Connection configuration                                                    ##
vcfa_host
vcfa_port
vcfa_csp_host                   # optional; set to the value of "vcfa_host"
vcfa_proxy_required
vcfa_proxy                      # used when "vcfa_proxy_required=true"
# "vcfa_auth_with_refresh_token" specifies the authentication type
vcfa_auth_with_refresh_token
vcfa_refresh_token              # used when "vcfa_auth_with_refresh_token=true"
vcfa_username                   # used when "vcfa_auth_with_refresh_token=false"
vcfa_password                   # used when "vcfa_auth_with_refresh_token=false"

## Content management configuration - used for import and clean up operations  ##
## (i.e. when "vcfaa_import_packages=true" or "vcfa_delete_content=true")      ##
vcfa_project_name
vcfa_org_name

## Import configuration - used only for import operation                       ##
## (i.e. when "vra_ng_import_packages=true")                                   ##
vcfa_import_overwrite_mode      # optional, can set value to "SKIP"
# "vcfa_vro_integration_name" specifies the integration endpoint for workflow
# catalog item and other resources that point to that type of integration.
# If the property is missing, the default name "embedded-VRO" is used
vcfa_vro_integration_name
# "vcfa_import_timeout" sets the timeout (in milliseconds) for the
# synchronization of the content source and custom forms
vcfa_import_timeout
# "vcfa_data.collection.delay.seconds" sets the delay (wait time in seconds)
# for the data collection of the Orchestrator integration so the import of
# Automation content that depends on Orchestrator objects can succeed.
# When the property is provided, the script forces data collection for the
# integration and only if this fails, the script uses the delay.
vcfa_data.collection.delay.seconds
vcfa_bp_unrelease_versions

#################################################################################
## Properties for VCF Operations Projects                                      ##
#################################################################################

## Operation flag                                                              ##
vrops_import_packages           # imports project bundle content

## Connection configuration                                                    ##
# HTTP-REST connection configuration                                            #
vrops_httpHost
vrops_httpPort
vrops_restUser
vrops_restPassword
vrops_restAuthProvider
vrops_restAuthSource

# SSH connection configuration                                                  #
vrops_sshPort
vrops_sshUsername
vrops_sshPassword

## Import configuration                                                        ##
vrops_dashboardUser
vrops_importDashboardsForAllUsers

#################################################################################
## Properties for VCF Operations for Logs Projects                             ##
#################################################################################

## Operation flag                                                              ##
vrli_import_packages            # imports project bundle content

## Connection configuration                                                    ##
# VCF Operations for Logs connection configuration                              #
vrli_server
vrli_port
vrli_username
vrli_password
vrli_provider

# VCF Operations integration connection configuration                           #
vrli_vrops_server
vrli_vrops_server_port
vrli_vrops_server_user
vrli_vrops_server_password
vrli_vrops_server_auth_source

## Import configuration                                                        ##
vrli_package_import_overwrite_mode

#################################################################################
## Properties for VCD Projects                                                 ##
#################################################################################

## Operation flag                                                              ##
vcd_import_packages             # imports project bundle content
# vcd_delete_old_versions       # clean up operation for VCD is not supported

## Connection configuration                                                    ##
vcd_server
vcd_port
vcd_username
vcd_password

## Import configuration                                                        ##
vcd_import_old_versions
# set "skip_vcd_import_old_versions" to opposite value of "vcd_import_old_versions"
skip_vcd_import_old_versions
vcd_import_overwrite_mode

#################################################################################
## Properties for SSH Projects                                                 ##
#################################################################################

## Operation flag                                                              ##
ssh_import_packages             # imports project bundle content

## Connection configuration                                                    ##
ssh_server
ssh_port
ssh_username
ssh_password

## Import configuration                                                        ##
ssh_directory

#################################################################################
## Properties for Running an Orchestrator Workflow                             ##
#################################################################################

## Operation flag                                                              ##
vro_run_workflow                # runs existing Orchestrator workflow
# Note that this operation is also available for project bundles that do not    #
# have Orchestrator content                                                     #

## Connection configuration                                                    ##
## Use connection configurations for Orchestrator instance, either embedded    ##
## (i.e. VCF Automation VM Apps) or standalone/external                        ##

## Workflow run configurations                                                 ##
vro_run_workflow_id
vro_run_workflow_input_file_path
vro_run_workflow_output_file_path
vro_run_workflow_err_file_path
vro_run_workflow_timeout

#################################################################################