blank_issues_enabled: false
contact_links:
  - name: 💬 Question
    url: https://github.com/vmware/build-tools-for-vmware-aria/discussions
    about: Please ask and answer questions in our GitHub Discussions.
