---
# Example blueprints:
# blueprint:
#  - Volume
#  - Machine
# Example subscriptions:
# subscription:
#  - subscription 1
#  - subscription 2
#  - subscription 3
# Example vra workflow Catalog Item
# catalog-item:
#   - source__Sum two numbers
# Example vra workflow Content SOurce
# content-source:
#   - source
# Example Catalog Entitlement:
# catalog-entitlement
#  - content source entitlement 1
#  - content source entitlement 2
# Example Property Groups:
# property-group:
#  - property-group-1
# policy:
#   content-sharing: 
#     - policy name 1
#     - policy name 2

blueprint:
subscription:
flavor-mapping:
  - small
  - medium
image-mapping: []
storage-profile: []
region-mapping:
  cloud-account-tags:
    export-tag: "env:dev"
    import-tags: ["env:dev", "env:test"]
catalog-item:
custom-resource:
resource-action:
catalog-entitlement:
content-source:
property-group:
policy:
  content-sharing:
