services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    networks:
      infranet:
        ipv4_address: 172.19.0.10
    ports:
      - 80:80 # Web Interface
    hostname: "infra.corp.local"
    volumes:
      - "./nginx:/etc/nginx/"
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    hostname: "nexus.corp.local"
    environment:
      NEXUS_CONTEXT: nexus
    networks:
      infranet:
        ipv4_address: 172.19.0.11
    extra_hosts:
      - "gitlab.corp.local:172.19.0.12"
    ports:
     - 8081:8081 # Web Interfac
    volumes:
      - "nexus-data:/var/sonatype/work"
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  gitlab:
    image: gitlab/gitlab-ce # Linux
    container_name: gitlab-ce
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://infra.corp.local/gitlab'
    networks:
      infranet:
        ipv4_address: 172.19.0.12
    extra_hosts:
      - "infra.corp.local:172.19.0.10"
    ports:
      - 8082:80 # Web Interface
      - 8022:22 # SSH
    hostname: "gitlab.corp.local"
    volumes:
      - "gitlab-config:/var/gitlab/config"
      - "gitlab-data:/var/gitlab/data"
      - "gitlab-log:/var/gitlab/log"
  gitlab-runner:
    image: gitlab-runner # Custom image build from the gitlab-runner directory
    build:
      context: gitlab-runner
      dockerfile: ./gitlab-runner/Dockerfile
    container_name: gitlab-runner
    restart: always
    hostname: "gitlab-runner.corp.local"
    networks:
      infranet:
        ipv4_address: 172.19.0.13
    extra_hosts:
      - "infra.corp.local:172.19.0.10"
      - "nexus.corp.local:172.19.0.11"
      - "gitlab.corp.local:172.19.0.12"
    ports:
      - 2811:2811
    volumes:
      - "./.m2:/home/gitlab-runner/.m2"
      - "gitlab-runner-config:/var/gitlab-runner/config"
      - "gitlab-runner-opt:/var/gitlab-runner/opt"
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  nexus-data: {}
  gitlab-config: {}
  gitlab-data: {}
  gitlab-log: {}
  gitlab-runner-config: {}
  gitlab-runner-opt: {}
networks:
  infranet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24
