name: Build Project

on:
  pull_request:
  push:
    branches:
      - "main" # trigger the workflow for main branch
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        java: ["17","21"]
        maven: ["3.9.2"]
        node: ["16.20.2"]
        node_vmware_samples: ["14.17.1"]
        os: ["ubuntu-latest"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout vmware/build-tools-for-vmware-aria repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.7.0
        with:
          java-version: ${{ matrix.java }}
          java-distribution: "temurin"
          maven-version: ${{ matrix.maven }}

      - name: Install xmllint
        run: sudo apt-get install libxml2-utils
        
      - name: Install run-script-os@1.1.6
        run: npm install -g run-script-os@1.1.6
  
      - name: Print versions
        run: |
          echo "-------------------------------------------"
          echo "-----------< TOOLS AND VERSIONS >----------"
          git --version
          java -version 2>&1
          mvn --version
          echo "node version: $(node --version)"
          echo "npm version: $(npm --version)"
          pip3 --version
          python --version
          pwsh --version
          gpg --version | head -n 1
          openssl version
          xmllint --version 2>&1 | head -n 1
          echo "Installed global npm packages:"
          npm list -g --depth=0
          echo "-------------------------------------------"
          echo "-------------------------------------------"

      - name: Get IAC version
        run: echo "IAC_VERSION=$(mvn help:evaluate -Dexpression=revision -q -DforceStdout)" >> $GITHUB_ENV

      - name: Replace variables in settings.xml
        run: |
          sed -i "s/{{ IAC_VERSION }}/${{ env.IAC_VERSION }}/g" .m2/settings.xml
          sed -i "s/{{ OSSRH_USERNAME }}/${{ secrets.OSSRH_USERNAME }}/g" .m2/settings.xml
          sed -i "s/{{ OSSRH_PASSWORD }}/${{ secrets.OSSRH_PASSWORD }}/g" .m2/settings.xml

      - name: Import GPG Key
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Set default env GPG_PASSPHRASE
        run: echo "GPG_PASSPHRASE=''" >> $GITHUB_ENV

      - name: Set env GPG_PASSPHRASE if main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "GPG_PASSPHRASE=${{ secrets.GPG_PASSPHRASE }}" >> $GITHUB_ENV

      - name: Test
        run: |
          echo "testing start"

          if [ "${{ matrix.node }}" = "16.20.2" ] && [ "${{ matrix.java }}" = "17" ]; then
            echo "first is 17"
          else
            echo "first is not 17"
          fi

          if [ "${{ matrix.java }}" = "21" ] && [ "${{ matrix.node }}" = "16.20.2" ]; then
            echo "second is 21"
          else
            echo "second is not 21"
          fi

          echo "testing end"

      - name: Test contain 17
        if: ${{ contains(env.IAC_VERSION, '-SNAPSHOT') && matrix.java == 17 }}
        run: |
          echo "we have 17 in contains test"

      - name: Test contain 17 str
        if: ${{ contains(env.IAC_VERSION, '-SNAPSHOT') && matrix.java == "17" }}
        run: |
          echo "we have 17 in contains test"          

      - name: Test contain 21
        if: ${{ contains(env.IAC_VERSION, '-SNAPSHOT') && matrix.java == 21 }}
        run: |
          echo "we have 21 in contains test"

      - name: Test contain 21 string
        if: ${{ contains(env.IAC_VERSION, '-SNAPSHOT') && matrix.java == "21" }}
        run: |
          echo "we have 21 in contains test"

      - name: Just java 17
        if: ${{ matrix.java == 17 }}
        run: |
          echo "we have 17 without contains test"
