name: "Build MkDocs"

on:
  push:
    # paths:
    #   - 'mkdocs/**'
    #   - 'mkdocs.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  mkdocs:
    name: Build and Deploy MkDocs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Dependencies
        run: |
          pip install mkdocs-material \
            mkdocs-awesome-pages-plugin \
            mkdocs-macros-plugin \
            mkdocs-include-markdown-plugin \
            mike 

      - name: Configure Git user
        run: |
          git config --global user.email "ci-admin@vmware.com"
          git config --global user.name "WWCoE CI admin"

      - name: Update Latest Release Variable
        run: |
          IAC_LATEST_RELEASE=$(git tag --sort=-version:refname | head -n 1 | cut -c 2-)
          echo "Latest Release: $IAC_LATEST_RELEASE"
          yq eval ".extra.iac.latest_release = \"$IAC_LATEST_RELEASE\"" -i mkdocs.yml

      - name: Build Docs (All Branches)
        run: mkdocs build

      - name: Deploy Docs (Main Branch Only)
        if: github.ref == 'refs/heads/main'
        run: mkdocs gh-deploy --force
